export type MockDataTrainings = {
    names:string[],
    backgrounds:string[],
    levels:string[],
    workouts:string[],
    times:string[],
    prices:number[],
    calories:number[],
    descriptions:string[],
    genders:string[],
    videos:string[],
    ratings:number[],
    trainers:string[],
    specials:boolean[],
    }
